config/routes.rb
Rails.application.routes.draw do
  resources :screenshots, except: [:show]
  resource :profile, only: [:show, :update]

  devise_for :users do
    get "/login" => "devise/sessions#new"
  end

  get 'pages/home'
  get 'ss/:sid' => 'screenshots#show', as: :share

  root 'pages#home'

end

app/models/screenshot.rb
class Screenshot < ActiveRecord::Base

  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>" }, :default_url => "default.jpg"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :url, presence: :true, url: true
  validates_uniqueness_of :url, scope: :user_id

  before_create :set_substitute_id


  #  ====================
  #  = Instance methods =
  #  ====================
  def update_views
    self.update_attribute :views_count, (views_count + 1)
  end

  def sid
    substitute_id
  end

  def set_substitute_id
    generate_substitute_id
    until self.class.where(substitute_id: self.substitute_id).blank?
      generate_substitute_id
    end
  end

  #  =====================
  #  = Protected methods =
  #  =====================
  protected

    def generate_substitute_id
      self.substitute_id = SecureRandom.urlsafe_base64(8).gsub('-','').gsub('_','')
    end


end

# == Schema Information
#
# Table name: screenshots
#
#  id                 :integer          not null, primary key
#  substitute_id      :string(255)
#  name               :string(255)
#  views_count        :integer          default(0)
#  url                :string(255)
#  user_id            :integer
#  created_at         :datetime
#  updated_at         :datetime
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :screenshots
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  name                   :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  #  ===================
  #  = Private methods =
  #  ===================
  private
    def after_sign_in_path_for(resource)
      new_screenshot_url
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authenticate_user!

  def home
    redirect_to new_screenshot_url if user_signed_in?
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show; end

  def update
    current_user.update_attribute :name, profile_params[:name]
    redirect_to :back
  end

  #  ===================
  #  = Private methods =
  #  ===================
  private
    # Only allow a trusted parameter "white list" through.
    def profile_params
      params.require(:profile).permit(:name)
    end


end

app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController
  before_action :set_screenshot, only: [:edit, :update, :destroy]
  skip_before_filter :authenticate_user!, only: [:show]

  # GET /screenshots
  def index
    redirect_to action: :new
  end

  # GET /screenshots/1
  def show
    @screenshot = Screenshot.find_by_substitute_id!(params[:sid])
    verify_session_and_update_views
  end

  # GET /screenshots/new
  def new
    @screenshots = current_user.screenshots
    @screenshot = Screenshot.new
  end

  # GET /screenshots/1/edit
  def edit;end

  # POST /screenshots
  def create
    @screenshot = current_user.screenshots.build(screenshot_params)
    if @screenshot.valid?
      begin
        capture_screenshot_and_set_image
      rescue => e
        redirect_to :back , error: "Error occured: #{e}"
        return
      end
      @screenshot.save
      redirect_to [:edit, @screenshot], notice: 'Screenshot was successfully created.'
    else
      @screenshots = current_user.screenshots
      render :new
    end
  end

  # PATCH/PUT /screenshots/1
  def update
    if @screenshot.update(screenshot_params)
      redirect_to [:edit, @screenshot], notice: 'Screenshot was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /screenshots/1
  def destroy
    @screenshot.destroy
    redirect_to action: :new, notice: 'Screenshot was successfully destroyed.'
  end

  #  ===================
  #  = Private methods =
  #  ===================
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screenshot
      @screenshot = current_user.screenshots.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def screenshot_params
      params.require(:screenshot).permit(:name, :url, :image)
    end

    def verify_session_and_update_views
      unless session[:viewed_for]
        @screenshot.update_views
        session[:viewed_for] = @screenshot.id
      end
    end

    def capture_screenshot_and_set_image
      f = Screencap::Fetcher.new(@screenshot.url)
      save_path = Rails.root.join("public/screenshots/#{current_user.id}/")
      FileUtils.mkpath save_path
      save_path = save_path + 'last_screenshot.png'
      @screenshot.image = f.fetch(output: save_path)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : 'ScreenShotz' %></title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="large-12 columns">

        <%= render 'shared/header' %>
        <%= render 'shared/flash_messages' %>
        <%= yield %>


        <%= render 'shared/footer' %>

        <% if Rails.env.production? %>
          <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-55019658-1', 'auto');
            ga('send', 'pageview');

          </script>
        <% end %>

      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<br><br>
<center>
  <h1>Welcome to Screenshotz</h1>
  <br><br><br><br>
  <h2><%= link_to 'Try it Now :)', new_user_registration_url, class: :button %></h2>
</center>

app/views/profiles/show.html.erb
<br><br>
<div class="row">
  <div class="large-8 columns">
      <div class="row collapse prefix-radius">
        <div class="small-2 columns">
          <span class="prefix">Email</span>
        </div>
        <div class="small-8 columns">
          <%= text_field_tag :email, current_user.email, disabled: :disabled %>
        </div>
        <div class="small-2 columns">
          <span></span>
        </div>
      </div>
  </div>
</div>
<br>

<div class="row">
  <div class="large-8 columns">
    <%= form_for current_user, as: :profile, url: profile_path do |f| %>
      <div class="row collapse prefix-radius">
        <div class="small-2 columns">
          <span class="prefix">Name</span>
        </div>
        <div class="small-8 columns">
          <%= f.text_field :name %>
        </div>
        <div class="small-2 columns">
          <%= f.submit 'Ok', class: 'button postfix' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/screenshots/_form.html.erb
<%= form_for(@screenshot) do |f| %>
  <% if @screenshot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@screenshot.errors.count, "error") %> prohibited this screenshot from being saved:</h2>

      <ul>
      <% @screenshot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% unless @screenshot.new_record? %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/screenshots/_screenshot.html.erb
<% if screenshot.persisted? %>
  <div class="large-4 small-6 columns">
    <%= link_to image_tag( screenshot.image(:medium)), [:edit, screenshot] %>

    <div class="panel">
      <h5><%= screenshot.name || 'Unnamed' %></h5>
      <h6 class="subheader"><strong>views: </strong> <%= screenshot.views_count %></h6>
    </div>

  </div>
<% end %>

app/views/screenshots/_screenshot_errors.html.erb
<div id="error_explanation">
  <h2><%= pluralize(screenshot.errors.count, "error") %> prohibited this screenshot from being saved:</h2>

  <ul>
  <% screenshot.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>

app/views/screenshots/edit.html.erb
 <div class="row">
  <div class="large-4 columns">
    <%= form_for(@screenshot) do |f| %>
      <div class="row collapse prefix-radius">
        <div class="small-2 columns">
          <span class="prefix">Name</span>
        </div>
        <div class="small-8 columns">
          <%= f.text_field :name %>
        </div>
        <div class="small-2 columns">
          <%= f.submit 'Ok', class: 'button postfix' %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="large-4 columns">
    <div class="row collapse postfix-radius">
      <div class="small-3 columns">
        <span class="prefix">Share url:</span>
      </div>
      <div class="small-9 columns">
        <%= text_field_tag :abcd, share_url( @screenshot.sid) %>
      </div>
    </div>
  </div>
  <div class="large-4 columns">
    <div class="row collapse postfix-radius">
      <div class="small-4 columns">
          <span class="label secondary"><big>Views:</big></span> <span class="label round radius"><big><%= @screenshot.views_count %></big></span>
      </div>
      <div class="small-8 columns" style="overflow: scroll;">
        <!-- <span class="label secondary"><big>URL:</big></span> -->
        <span><code><%= @screenshot.url %></code></span>
      </div>
    </div>
  </div>
</div>

<hr>
<%= link_to 'Delete', [@screenshot], class: 'button tiny alert', style: 'float: right;', method: :delete, data: { confirm: 'Are you sure you wanna delete this?' } %>

<%= image_tag @screenshot.image.url %>

app/views/screenshots/new.html.erb
<div class="row">

  <div class="large-4 small-12 columns">
    <div class="row">
      <div class="large-12 columns">
        <div class="panel">
          <div class="row">
            <div class="large-12 small-6 columns">
              <strong>Take a ScreenShot Now<hr/></strong>

                <%= form_for(@screenshot) do |f| %>
                  <%= render 'screenshot_errors', screenshot: @screenshot if @screenshot.errors.any? %>
                  <div class="row">
                    <div class="large-12 columns">
                      <div class="row collapse">
                        <div class="small-10 columns">
                          <%= f.text_field :url, placeholder: 'http://www.google.com' %>
                        </div>
                        <div class="small-2 columns">
                          <%= f.submit 'Go', class: 'button postfix' %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="large-8 columns">
    <div class="row">
      <% if @screenshots.present? %>
        <%= render partial: 'screenshot', collection: @screenshots %>
      <% else %>
        <br>
        <center><p> No ScreenShot Available :(</p></center>
      <% end %>
    </div>
  </div>
</div>

app/views/screenshots/show.html.erb
<br>
<%= image_tag @screenshot.image.url %>

app/views/shared/_flash_messages.html.erb
<% if notice %>
  <div data-alert class="alert-box info radius"><%= notice %><a href="#" class="close">&times;</a></div>
<% end %>

<% if alert %>
  <div data-alert class="alert-box alert radius"><%= alert %><a href="#" class="close">&times;</a></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="row">
  <div class="large-12 columns"><hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>© Copyright, no one at all ;)</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="row">
  <div class="large-4 columns">
    <h1><%= link_to image_tag('http://placehold.it/400x100&text=ScreenShotz'), root_path %></h1>
  </div>
  <div class="large-8 columns">
    <ul class="right button-group">
      <% if user_signed_in? %>
        <li><%= link_to 'Profile', profile_path, class: :button %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, class: :button %></li>
      <% else %>
        <li><%= link_to'Log in', new_user_session_path, class: :button %></li>
        <li><%= link_to 'Sign up', new_user_registration_url, class: :button %></li>
      <% end %>

    </ul>
  </div>
</div>